#+TITLE: Princeton Emacs title
#+AUTHOR: Jonathan Chu
#+EMAIL: jonathan@princetonemacs.org

#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: /

* Meetups
:PROPERTIES:
:EXPORT_HUGO_SECTION: meetups
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :omit_header_text true
:END:
** Meetup #1 - June 17, 2019
:PROPERTIES:
:EXPORT_DATE: 2019-06-17T00:00:00-04:00
:EXPORT_FILE_NAME: dont-use-emacs
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :featured_image /img/dont-use-emacs.png
:END:
For the very first Princeton Emacs meetup, Jonathan Chu thought it would be appropriate to title his talk “Don’t Use Emacs”.
#+hugo: more
Welcome Princeton Emacs meetup members! Let's kick things off by having a meet and greet to chat and get to know each other! I know not everyone will be an Emacs user, but I think that is great as we all have things to learn from each other.

There will be a quick high-level talk on Emacs and its history to get things going and then we can also talk about the direction we want to take this group, future meetup locations, and possible meeting space sponsors.

The title of this talk is tongue-in-cheek as we only scratched the surface talking about why Emacs rocks!

Slides - https://docs.google.com/presentation/d/1xMk1Q9dzTbixft1R7YQ2a6WRxKcOpJI3H0mFfZSBYbk/edit?usp=sharing

** Meetup #2 - August xx, 2019
:PROPERTIES:
:EXPORT_DATE: 2019-08-15T00:00:00-04:00
:EXPORT_FILE_NAME: second-meetup
:END:
Second meetup title goes here

Here is some more info on the second meetup.
