#+TITLE: Princeton Emacs title
#+AUTHOR: Jonathan Chu
#+EMAIL: jonathan@princetonemacs.org

#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: /

* Princeton Emacs
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_TYPE: homepage
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :description The Home of Princeton’s Newest and Most Exciting Emacs Community Meetup
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :omit_header_text true
:END:
** Welcome to Princeton Emacs.

** What is Princeton Emacs?
Well…you are!  Princeton Emacs is about the Emacs community right here in Princeton, New Jersey.  It's not about any one company or a core group of individuals. We were founded on the principle that everyone deserves to be treated with respect. We all deserve a safe, judgement free place to congregate—online, and in person.

Please see our code of conduct for complete details.

** You can find us here
*** Join us on [[https://www.meetup.com/Princeton-Emacs][Meetup.com]]
*** Follow us on Twitter [[https:/twitter.com/PrincetonEmacs][@PrincetonEmacs]]
*** Get in touch at [[mailto:organizers@princetonemacs.org][organizers@princetonemacs.org]]

** Call For Proposals!
Interested in speaking? Fill out this Google form and we’ll get in touch.
https://forms.gle/jqQ21CxYu8tZYe937

** Code of Conduct
Princeton Emacs is dedicated to providing a harassment-free meetup experience for everyone, regardless of gender, sexual orientation, disability, physical appearance, body size, race, religion, or anything else. We do not tolerate harassment of meetup participants in any form.

Harassment includes offensive verbal comments related to gender, sexual orientation, disability, physical appearance, body size, race, religion, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, derisive comments regarding technical background, and unwelcome sexual attention.

Participants asked to stop any harassing behavior are expected to comply immediately.

All communication should be appropriate for a professional audience including people of many different backgrounds. Sexual language and imagery is not appropriate for any meetup, including talks.

If a participant engages in harassing behavior, the meetup organizers may take any action they deem appropriate, including warning the offender or expulsion from the event with no refund (if applicable). In the event of serious infractions of the code of conduct, Princeton Emacs staff may share incident details and offenders’ names with third parties including but not limited to: venue staff, local law enforcement, and staff of other meetups/conferences. If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact a member of meetup staff immediately.

** Social Rules
#+attr_html: :class haha
In addition to having a code of conduct as an anti-harassment policy, we have a small set of social rules we follow. We lifted these rules from the Recurse Center, where we felt that they contributed enormously to a supportive, productive, and fun learning environment. We'd like Princeton Emacs to share that environment. These rules are intended to be lightweight, and to make more explicit certain social norms that are normally implicit. Most of our social rules really boil down to "don't be a jerk" or "don't be annoying." Of course, almost nobody sets out to be a jerk or annoying, so telling people not to be jerks isn't a very productive strategy.

https://www.recurse.com/social-rules

If you have any questions about any part of the code of conduct or Social Rules, please feel free to reach out to the meetup organizers (organizers@princetonemacs.org).

Contact Information

If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact one of the meetup organizers.

If the matter is especially urgent, please call/contact this individual:

    Jonathan Chu - (347) 503-9000

Meetup staff will be happy to help participants contact local law enforcement, provide escorts, or otherwise assist those experiencing harassment to feel safe for the duration of events. We value your attendance.

** Organizers

Jonathan Chu
https://jonathanchu.is/

* Meetups
:PROPERTIES:
:EXPORT_HUGO_SECTION: meetups
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :omit_header_text true
:END:
** Meetup #1 - June 17, 2019
:PROPERTIES:
:EXPORT_DATE: 2019-06-17T00:00:00-04:00
:EXPORT_FILE_NAME: first-meetup
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :featured_image /images/dont-use-emacs.png
:EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :omit_header_text true
:END:
Don’t Use Emacs
#+hugo: more
https://docs.google.com/presentation/d/1xMk1Q9dzTbixft1R7YQ2a6WRxKcOpJI3H0mFfZSBYbk/edit?usp=sharing
** Meetup #2 - July xx, 2019
:PROPERTIES:
:EXPORT_DATE: 2019-07-03T00:00:00-04:00
:EXPORT_FILE_NAME: second-meetup
:END:
Second meetup title goes here

Here is some more info on the second meetup.
** Meetup #3 - August xx, 2019
:PROPERTIES:
:EXPORT_DATE: 2019-08-03T00:00:00-04:00
:EXPORT_FILE_NAME: third-meetup
:END:
Third meetup title goes here

Here is some more info on the third meetup.
** Meetup #4 - September xx, 2019
:PROPERTIES:
:EXPORT_DATE: 2019-09-03T00:00:00-04:00
:EXPORT_FILE_NAME: fourth-meetup
:END:
Fourth meetup title goes here
Here is some more info on the fourth meetup.
