#+TITLE: Princeton Emacs title
#+AUTHOR: Jonathan Chu
#+EMAIL: jonathan@princetonemacs.org

#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: /
#+HUGO_MENU: :menu main

* Home
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_TYPE: homepage
:END:
** Welcome to Princeton Emacs.

** What is Princeton Emacs?

** You can find us here
*** Join us on [[https://www.meetup.com/Princeton-Emacs][Meetup.com]]
*** Follow us on Twitter [[https:/twitter.com/PrincetonEmacs][@PrincetonEmacs]]
*** Get in touch at [[mailto:organizers@princetonemacs.org][organizers@princetonemacs.org]]

** Call For Proposals!

** Code of Conduct
Princeton Emacs is dedicated to providing a harassment-free meetup experience for everyone, regardless of gender, sexual orientation, disability, physical appearance, body size, race, religion, or anything else. We do not tolerate harassment of meetup participants in any form.

Harassment includes offensive verbal comments related to gender, sexual orientation, disability, physical appearance, body size, race, religion, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, derisive comments regarding technical background, and unwelcome sexual attention.

Participants asked to stop any harassing behavior are expected to comply immediately.

All communication should be appropriate for a professional audience including people of many different backgrounds. Sexual language and imagery is not appropriate for any meetup, including talks.

If a participant engages in harassing behavior, the meetup organizers may take any action they deem appropriate, including warning the offender or expulsion from the event with no refund (if applicable). In the event of serious infractions of the code of conduct, Princeton Emacs staff may share incident details and offenders’ names with third parties including but not limited to: venue staff, local law enforcement, and staff of other meetups/conferences. If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact a member of meetup staff immediately.

** Social Rules

In addition to having a code of conduct as an anti-harassment policy, we have a small set of social rules we follow. We lifted these rules from the Recurse Center, where we felt that they contributed enormously to a supportive, productive, and fun learning environment. We'd like Princeton Emacs to share that environment. These rules are intended to be lightweight, and to make more explicit certain social norms that are normally implicit. Most of our social rules really boil down to "don't be a jerk" or "don't be annoying." Of course, almost nobody sets out to be a jerk or annoying, so telling people not to be jerks isn't a very productive strategy.

https://www.recurse.com/social-rules

If you have any questions about any part of the code of conduct or Social Rules, please feel free to reach out to the meetup organizers (organizers@princetonemacs.org).

Contact Information

If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact one of the meetup organizers.

If the matter is especially urgent, please call/contact this individual:

    Jonathan Chu - (347) 503-9000

Meetup staff will be happy to help participants contact local law enforcement, provide escorts, or otherwise assist those experiencing harassment to feel safe for the duration of events. We value your attendance.

** Organizers

Jonathan Chu
http://jonathanchu.is/
